
if GetPlatform() == Platform.Xbox360 then
	package.path = "Game:\\data\\Scripts\\Quests\\?.lua"
elseif GetPlatform() == Platform.Win32 then
	package.path = "data\\Scripts\\Quests\\?.lua"
end

RunScript("Quests/QuestManager.lua")
RunScript("Quests/LuaEnums.lua")
RunScript("Quests/GenericTriggers.lua")
RunScript("Quests/DemoStartupSettings.lua")
RunScript("Quests/SavedVariables.lua")
RunScript("Quests/MiscFunctions.lua")
RunScript("Quests/CommunityService.lua")
RunScript("Quests/ChapterProgress.lua")
RunScript("Quests/ScriptActivation.lua")
RunScript("Quests/Gameflow.lua")
RunScript("Quests/JobCoordinator.lua")
RunScript("Quests/JobCommonScript.lua")
RunScript("Quests/JobBlacksmithManager.lua")
RunScript("Quests/JobCookingManager.lua")
RunScript("Quests/JobLuteHeroManager.lua")
RunScript("Quests/JobExampleManager.lua")
RunScript("Quests/JobGeneratedManager.lua")
RunScript("Quests/JobGeneratedMetaManager.lua")
RunScript("Quests/QR200_RulingCivilManager.lua")
RunScript("Quests/QOTF_FetchManager.lua")
RunScript("Quests/QOTA_AssassinateManager.lua")
RunScript("Quests/QOTC_CourierManager.lua")
RunScript("Quests/QOTE_EscortManager.lua")
RunScript("Quests/QOTP_FetchPersonManager.lua")
RunScript("Quests/QOTM_PayMeMoneyManager.lua")
RunScript("Quests/QOTS_ShoppingListManager.lua")
RunScript("Quests/QOTA_AssassinateManager2.lua")
RunScript("Quests/QS_RelationshipQuestManager.lua")
RunScript("Quests/QRCH_RulerCreatureHunterManager.lua")
RunScript("Quests/QP_ProtestsQuestManager.lua")
RunScript("Quests/QDRAG_SlaveManager.lua")
RunScript("Quests/QDRAG_CriminalManager.lua")
RunScript("Quests/RegionLocking.lua")
RunScript("Quests/HeroTrackers.lua")
RunScript("Quests/ScriptDebug.lua")
RunScript("Miscellaneous/GuildNew.lua")
RunScript("Miscellaneous/GuildRoomsSingle.lua")
RunScript("Miscellaneous/GuildRoomsSingleRemote.lua")
RunScript("Miscellaneous/GuildCallbackFunctions.lua")
RunScript("Miscellaneous/GuildUtilityFunctions.lua")
RunScript("Miscellaneous/GuildItemListFunctions.lua")
RunScript("Miscellaneous/GuildButler.lua")
RunScript("Miscellaneous/GuildButlerTalkManager.lua")
RunScript("Miscellaneous/GuildButlerRoomEventMonitor.lua")
RunScript("Miscellaneous/GuildButlerRoomEventCustomFunctions.lua")
RunScript("Miscellaneous/GuildButlerSpeechSituationManager.lua")
RunScript("Miscellaneous/GuildTutorialCallbacks.lua")
RunScript("Miscellaneous/DLC_ItemAwardMonitor.lua")
RunScript("Miscellaneous/DLC1_Unlocks.lua")
RunScript("Miscellaneous/DLC_DogSkin_Unlocks.lua")
RunScript("Miscellaneous/DLC2_Unlocks.lua")
RunScript("Miscellaneous/NewGame.lua")
RunScript("Quests/ChapterProgress_DLC_EP1.lua")

-- Additional ScriptActivation
RunScript("Quests/scriptactivation_additional.lua")
