[package]
name = "korevm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Reader and disassembler for Fable III KoreVM Lua bytecode"

[[bin]]
name = "koredis"
path = "src/bin/koredis.rs"

[[bin]]
name = "koredec"
path = "src/bin/koredec.rs"

[dependencies]
