 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatYearOut')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtYearOut')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersYearOut')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsYearOut')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPoorF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPoorM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatMiddleF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPoshM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPoshF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatBanditM_1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatBanditM_2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatHighwaymanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatLucienGuardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatSpartanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWizardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatFarmerM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatFarmerF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatCultistEvilM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatMascotM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWhoreM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWhoreF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWigF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtCorsetF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtPoorF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtPoorM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtMiddleF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtPoshM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtPoshF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtBanditM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtWhoreM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingShirtWhoreF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatShortF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatPoorF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatMiddleF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatPoshM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatRangerM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatHighwayman')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatLucienGuardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatSpartanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatWizardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatCultistGoodM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatCultistEvilM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatMascotM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatAssassinM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersHotpantsF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPoorSkirtF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersMiddleSkirtF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPoshSkirtF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPoorM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPoshM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersBanditM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersRangerM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersHighwayman')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersLucienGuardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersSpartanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersGypsySkirtF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersWhoreSkirtF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersWhoreM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsHighF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPoorM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsBanditM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMiddleF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPoshM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsWhoreF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPoshF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsHighwaymanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsLucienGuardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMascotM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsSpartanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsCultistGoodM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesPoorM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesMiddleM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesWhoreF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesBanditM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesHighwaymanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesLucienGuardM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesSpartanM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesCultistGoodM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsAuroranF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPrincessF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPrincessPracticalF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPyjamasF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsRenegadeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsSkillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsStrengthF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsWillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingCoatRenegadeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesAuroranF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesPrincessF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesPrincessPracticalF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesRenegadeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesSkillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesStrengthF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesWillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatAuroranF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPrincessF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPrincessPracticalF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPyjamasF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatRenegadeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatSkillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatStrengthF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopAuroranF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPrincessF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPrincessPracticalF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPyjamasF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopRenegadeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopSkillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopStrengthF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopWillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersAuroranF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersGypsyF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPrincessF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPrincessPracticalF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPyjamasF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersRenegadeShortsF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersSkillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersStrengthF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersWillF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsAuroranM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsChicken')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsKingM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsMilitaryM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPrinceM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPrincePracticalM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsPyjamasM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsSkillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsStrengthM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesAuroranM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesChicken')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesKingM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesMilitaryM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesSkillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesStrengthM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingBootsQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGloveQueenF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingGlovesWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatAuroranM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatChicken')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatKingM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPrinceM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPrincePracticalM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatPyjamasM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatSkillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatStrengthM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingMaskRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopAuroranM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopChicken')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopKingM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopMilitaryM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPrinceM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPrincePracticalM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopPyjamasM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopSkillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopStrengthM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTopWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersAuroranM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersGypsyM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersKingM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersMilitaryM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPrinceM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPrincePracticalM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersPyjamasM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersRenegadeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersSkillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersStrengthM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingTrousersWillM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingMaskMasqueradeF')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingMaskMasqueradeM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingHatCook')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectAccessoryEyepatch')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectAccessoryBallroomMask')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectAccessoryHighwaymanMask')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeRed')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeOrange')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeBrown')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeYellow')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeLime')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeGreen')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeTurquoise')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeBlue')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeCream')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyePurple')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeWhite')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyePink')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeBlack')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeGrey')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeHotPink')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryDyeKhaki')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletEnflame')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletLightning')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletSwords')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletVortex')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletIceStorm')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectClothingSpellGauntletForcePush')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3Standard')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3ShortPonyTail')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3ShortFringed')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3Mohawk')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3LongThick')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3BaldDread')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3Bob')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3Long')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3LongBun')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3ShortBun')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3TiedBun')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectHairF3YoungHero')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3Beard')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3Full')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3LongTied')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3Mouth')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3Muttons')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3Tache')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3TacheBeard')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectBeardF3TacheSidies')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupBeauty1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupBeauty2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupEgyptian1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupEgyptian2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupGeisha1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupGeisha2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupGoth')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupGypsy')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupHarlequin')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupMarcelM')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupMoulinRouge')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupOutOfAfrica')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupProstitute')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupRenegade1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupRenegade2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupRenegade3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupRorscharch')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupStandard1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectMakeupStandard2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightAuroran')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightDweller')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightGuild')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackGuild2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightMilitary')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightNature')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightOldKingdom')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightRoyal')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceSE6')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE1')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE2')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE3')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE4')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE5')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmRightSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooArmLeftSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegRightSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooLegLeftSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooChestSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooBackSE7')
 Inventory.AddItemOfType(GetLocalHero(), 'ObjectTattooFaceSE7')
 local fillExpendableItems = {
	'ObjectInventoryGiftChessboard',
	'ObjectInventoryGiftChocolates',
	'ObjectInventoryGiftFlowers',
	'ObjectInventoryGiftGoblet',
	'ObjectInventoryGiftHandMirror',
	'ObjectInventoryGiftJewellery',
	'ObjectInventoryGiftPerfume',
	'ObjectInventoryGiftFruitBowlSilver',
	'ObjectInventoryGiftRing',
	'ObjectInventoryGiftToyBow',
	'ObjectInventoryGiftToyGun',
	'ObjectInventoryGiftToyHorse',
	'ObjectInventoryGiftToyPorcelainDoll',
	'ObjectInventoryGiftToyRagDoll',
	'ObjectInventoryGiftToySword',
	'ObjectInventoryGiftToyTeddyBear',
	'ObjectInventoryGiftGemAmethyst',
	'ObjectInventoryGiftGemDiamond',
	'ObjectInventoryGiftGemEmerald',
	'ObjectInventoryGiftGemJet',
	'ObjectInventoryGiftGemRuby',
	'ObjectInventoryGiftGemPearl',
	'ObjectInventoryGiftGemTopaz',
	'DoubleBedLevel1',
	'DoubleBedLevel2',
	'DoubleBedLevel3',
	'DoubleBedLevel4',
	'DoubleBedLevel5',
	'BedsideTableLevel1',
	'BedsideTableLevel2',
	'BedsideTableLevel3',
	'BedsideTableLevel4',
	'BedsideTableLevel5',
	'ComfyChairLevel1',
	'ComfyChairLevel2',
	'ComfyChairLevel3',
	'ComfyChairLevel4',
	'ComfyChairLevel5',
	'DeskTableLevel1',
	'DeskTableLevel2',
	'DeskTableLevel3',
	'DeskTableLevel4',
	'DeskTableLevel5',
	'LightFixingLevel1',
	'LightFixingLevel2',
	'LightFixingLevel3',
	'LightFixingLevel4',
	'LightFixingLevel5',
	'CollectablePainting_Ben',
	'CollectablePainting_Elise',
	'CollectablePainting_Elliot',
	'CollectablePainting_Logan',
	'CollectablePainting_Page',
	'CollectablePainting_Sabine',
	'CollectablePainting_Saker',
	'CollectablePainting_Swift',
	'CollectablePainting_Theresa',
	'CollectablePainting_Walter'
	}

	for key,value in pairs(fillExpendableItems) do
		while ((Inventory.GetNumberOfItemsOfType(GetLocalHero(), value)) < 5)
			do
			Inventory.AddItemOfType(GetLocalHero(), value)
		end
	end
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleSwiftIrregular')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleSkormJustice')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleSimmonsShotgun')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleScattershot')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleSakerFlintlock')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleMolynator')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleMarksman')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleHeroCompanion')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleFacemelter')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleEthelbertBoner')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleEqualiser')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleDefender')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryRifleArkwrightFlintlock')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolSailorGeriShooter')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolPerforator')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolMiriansMutilator')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolIceMaiden')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolHolyVengeance')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolGnomewrecker')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolDragonstomper')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolDesertFury')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolChickenbane')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolBriarsBlaster')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolBonesmasher')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolBloodcraver')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryPistolBarnumificator')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerChampion')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerAbsolver')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerWillmageddon')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerTwatter')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerTrollblight')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerSorrowsFist')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerScytheHammer')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerMalletsMallet')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerLunariumPounder')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerJackHammer')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerFaerie')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerDragonboneHammer')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerAuroraShield')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerAnwarGlory')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerTenderiser')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordShardborne')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordChanneler')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordInquisitor')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordWolfsbane')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordThunderblade')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordSwingingSword')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordSouldrinker')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordSlimquick')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordPorkSword')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordMrStabby')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordMogoShafter')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordMerchantsBodyguard')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordFishknife')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordCasanova')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordBeadleCutlass')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordBaronSlayer')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordAvoLamentation')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordDonorKebab')
 Debug.GiveHeroWeapon('ObjectInventoryLegendarySwordThundaraga')
 Debug.GiveHeroWeapon('ObjectInventoryLegendaryHammerHammerOfTheWhale')
 while ((Inventory.GetNumberOfItemsOfType(GetLocalHero(), 'ObjectInventoryPotionHealth')) < 100)
	do
	Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryPotionHealth')
end

while ((Inventory.GetNumberOfItemsOfType(GetLocalHero(), 'ObjectInventoryPotionSlowTime')) < 100)
	do
	Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryPotionSlowTime')
end

while ((Inventory.GetNumberOfItemsOfType(GetLocalHero(), 'ObjectInventoryPotionDeadRising')) < 100)
	do
	Inventory.AddItemOfType(GetLocalHero(), 'ObjectInventoryPotionDeadRising')
end